[workspace]
resolver = "3"
members = ["plugins/*", "sleeves/*"]

[workspace.package]
edition = "2024"
rust-version = "1.96"
version = "0.0.0"
publish = false

[workspace.dependencies]
spin = { version = "0.10", default-features = false, features = [
  "mutex",
  "spin_mutex",
] }
wit-bindgen = { version = "0.62", features = ["async"] }

[workspace.lints.rust]
unsafe_code = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
pedantic = "warn"

[profile.release]
panic = "abort"
