[package]
name = "sleeve-host"
publish.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
sha2.workspace = true
tokio.workspace = true
wac-graph.workspace = true
wasmparser.workspace = true
wasmtime = { workspace = true, features = ["cranelift"] }
wasmtime-wasi.workspace = true
wasmtime-wasi-http.workspace = true

[dev-dependencies]
file-scenarios = { path = "../../support/file-scenarios" }
guest-build = { path = "../../support/guest-build" }
http-scenarios = { path = "../../support/http-scenarios" }
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
