[package]
name = "passthrough-sleeve"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
sleeve-core = { path = "../../../crates/sleeve-core" }
wit-bindgen.workspace = true

[lints]
workspace = true
