[workspace]
resolver = "3"
members = ["policy", "sleeve"]

[workspace.package]
edition = "2024"
rust-version = "1.96"
version = "0.0.0"
publish = false

[workspace.dependencies]
wit-bindgen = { version = "0.62", features = [
  "async",
  "async-spawn",
  "inter-task-wakeup",
] }

[workspace.lints.rust]
unsafe_code = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
pedantic = "warn"

[profile.release]
panic = "abort"
