[package]
name = "http-ifc"
publish.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
guest-build = { path = "../../support/guest-build" }
http-scenarios = { path = "../../support/http-scenarios" }
sleeve-host = { path = "../../crates/sleeve-host" }
tokio.workspace = true

[lints]
workspace = true
